# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from youtube_data_v3.models.processing_details import ProcessingDetails


class TestProcessingDetails(unittest.TestCase):
    """ProcessingDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessingDetails:
        """Test ProcessingDetails
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProcessingDetails`
        """
        model = ProcessingDetails()
        if include_optional:
            return ProcessingDetails(
                processing_status = 'succeeded',
                processing_progress = youtube_data_v3.models.processing_details_processing_progress.ProcessingDetails_processingProgress(
                    parts_total = 56,
                    parts_processed = 56,
                    time_left_ms = 56, ),
                processing_failure_reason = '',
                file_details_availability = '',
                processing_issues_availability = '',
                tag_suggestions_availability = '',
                editor_suggestions_availability = '',
                thumbnails_availability = ''
            )
        else:
            return ProcessingDetails(
        )
        """

    def testProcessingDetails(self):
        """Test ProcessingDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
