# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from youtube_data_v3.models.file_details_video_streams_inner import (
    FileDetailsVideoStreamsInner,
)


class TestFileDetailsVideoStreamsInner(unittest.TestCase):
    """FileDetailsVideoStreamsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileDetailsVideoStreamsInner:
        """Test FileDetailsVideoStreamsInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FileDetailsVideoStreamsInner`
        """
        model = FileDetailsVideoStreamsInner()
        if include_optional:
            return FileDetailsVideoStreamsInner(
                width_pixels = 56,
                height_pixels = 56,
                frame_rate_fps = 1.337,
                aspect_ratio = 1.337,
                codec = '',
                bitrate_bps = 56,
                rotation = 'none',
                vendor = ''
            )
        else:
            return FileDetailsVideoStreamsInner(
        )
        """

    def testFileDetailsVideoStreamsInner(self):
        """Test FileDetailsVideoStreamsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
