# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from youtube_data_v3.models.caption_snippet import CaptionSnippet


class TestCaptionSnippet(unittest.TestCase):
    """CaptionSnippet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaptionSnippet:
        """Test CaptionSnippet
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CaptionSnippet`
        """
        model = CaptionSnippet()
        if include_optional:
            return CaptionSnippet(
                video_id = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                track_kind = 'standard',
                language = '',
                name = '',
                audio_track_type = 'unknown',
                is_cc = True,
                is_large = True,
                is_easy_reader = True,
                is_draft = True,
                is_auto_synced = True,
                status = 'failed',
                failure_reason = 'processingFailed'
            )
        else:
            return CaptionSnippet(
        )
        """

    def testCaptionSnippet(self):
        """Test CaptionSnippet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
