# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from youtube_data_v3.models.file_details import FileDetails


class TestFileDetails(unittest.TestCase):
    """FileDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileDetails:
        """Test FileDetails
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FileDetails`
        """
        model = FileDetails()
        if include_optional:
            return FileDetails(
                file_name = '',
                file_size = 56,
                file_type = 'video',
                container = '',
                video_streams = [
                    youtube_data_v3.models.file_details_video_streams_inner.FileDetails_videoStreams_inner(
                        width_pixels = 56,
                        height_pixels = 56,
                        frame_rate_fps = 1.337,
                        aspect_ratio = 1.337,
                        codec = '',
                        bitrate_bps = 56,
                        rotation = 'none',
                        vendor = '', )
                    ],
                audio_streams = [
                    youtube_data_v3.models.file_details_audio_streams_inner.FileDetails_audioStreams_inner(
                        channel_count = 56,
                        codec = '',
                        bitrate_bps = 56,
                        vendor = '', )
                    ],
                duration_ms = 56,
                bitrate_bps = 56,
                creation_time = ''
            )
        else:
            return FileDetails(
        )
        """

    def testFileDetails(self):
        """Test FileDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
