# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from youtube_data_v3.models.snippet import Snippet


class TestSnippet(unittest.TestCase):
    """Snippet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Snippet:
        """Test Snippet
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Snippet`
        """
        model = Snippet()
        if include_optional:
            return Snippet(
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                channel_id = '',
                title = '',
                description = '',
                thumbnails = {
                    'key' : youtube_data_v3.models.thumbnail.Thumbnail(
                        url = '',
                        width = 56,
                        height = 56, )
                    },
                channel_title = '',
                tags = [
                    ''
                    ],
                category_id = '',
                live_broadcast_content = 'live',
                default_language = '',
                localized = youtube_data_v3.models.localized.Localized(
                    title = '',
                    description = '', ),
                default_audio_language = ''
            )
        else:
            return Snippet(
        )
        """

    def testSnippet(self):
        """Test Snippet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
