repos:
  - repo: local
    hooks:
      - id: hide-secret
        name: Hide Files using Git Secret
        entry: make hide
        language: system
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/guid-empty/flutter-dependency-validation-pre-commit
    rev: "4663b743f807eaa0ee1309016f5a6d20b9bb1b13"
    hooks:
      - id: flutter-dependency-validation
  - repo: https://github.com/fluttercommunity/import_sorter
    rev: 'f350497a11b1285c695595049e95a420068e7a9f'
    hooks:
      - id: flutter-import-sorter
  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter analyze
        language: system
        entry: flutter analyze
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
