// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfwr-xpQAhrapakYM51-NTo39R8s0x1g',
    appId: '1:1009724725603:web:d84e66affa6ff5abef1b56',
    messagingSenderId: '1009724725603',
    projectId: 'yomutube-f5b5d',
    authDomain: 'yomutube-f5b5d.firebaseapp.com',
    storageBucket: 'yomutube-f5b5d.appspot.com',
    measurementId: 'G-TS09HM9W19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8asyolDF5vQxKQTWUwqqlHWbUuPnHEzo',
    appId: '1:1009724725603:android:fd2fb9957825f34aef1b56',
    messagingSenderId: '1009724725603',
    projectId: 'yomutube-f5b5d',
    storageBucket: 'yomutube-f5b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRzl9xfqvrYim5D-aSdbJXUGf7uvnj1EY',
    appId: '1:1009724725603:ios:7895dfaced30e742ef1b56',
    messagingSenderId: '1009724725603',
    projectId: 'yomutube-f5b5d',
    storageBucket: 'yomutube-f5b5d.appspot.com',
    iosClientId: '1009724725603-5eo1c2rq41mh3pg02rud2jfng1j74s1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.yomutube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRzl9xfqvrYim5D-aSdbJXUGf7uvnj1EY',
    appId: '1:1009724725603:ios:898b28ae05294b88ef1b56',
    messagingSenderId: '1009724725603',
    projectId: 'yomutube-f5b5d',
    storageBucket: 'yomutube-f5b5d.appspot.com',
    iosClientId: '1009724725603-t0tel20hvm048vjnf88ferhnhlecbd0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.yomutube.RunnerTests',
  );
}
