# coding: utf-8
# flake8: noqa
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
# import models into model package
from openapi_client.models.caption import Caption
from openapi_client.models.caption_list import CaptionList
from openapi_client.models.caption_snippet import CaptionSnippet
from openapi_client.models.content_details import ContentDetails
from openapi_client.models.content_details_region_restriction import (
    ContentDetailsRegionRestriction,
)
from openapi_client.models.content_rating import ContentRating
from openapi_client.models.file_details import FileDetails
from openapi_client.models.file_details_audio_streams_inner import (
    FileDetailsAudioStreamsInner,
)
from openapi_client.models.file_details_video_streams_inner import (
    FileDetailsVideoStreamsInner,
)
from openapi_client.models.live_streaming_details import LiveStreamingDetails
from openapi_client.models.localization_value import LocalizationValue
from openapi_client.models.localized import Localized
from openapi_client.models.page_info import PageInfo
from openapi_client.models.player import Player
from openapi_client.models.processing_details import ProcessingDetails
from openapi_client.models.processing_details_processing_progress import (
    ProcessingDetailsProcessingProgress,
)
from openapi_client.models.recording_details import RecordingDetails
from openapi_client.models.snippet import Snippet
from openapi_client.models.statistics import Statistics
from openapi_client.models.status import Status
from openapi_client.models.suggestions import Suggestions
from openapi_client.models.suggestions_tag_suggestions_inner import (
    SuggestionsTagSuggestionsInner,
)
from openapi_client.models.thumbnail import Thumbnail
from openapi_client.models.topic_details import TopicDetails
from openapi_client.models.video import Video
from openapi_client.models.video_category import VideoCategory
from openapi_client.models.video_category_list import VideoCategoryList
from openapi_client.models.video_category_snippet import VideoCategorySnippet
from openapi_client.models.video_list import VideoList
