# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Field
from pydantic import StrictStr

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ContentRating(BaseModel):
    """
    Specifies the ratings that the video received under various rating schemes.
    """  # noqa: E501

    acb_rating: Optional[StrictStr] = Field(
        default=None, description="The ACB rating of the content.", alias="acbRating"
    )
    agcom_rating: Optional[StrictStr] = Field(
        default=None,
        description="The AGCOM rating of the content.",
        alias="agcomRating",
    )
    anatel_rating: Optional[StrictStr] = Field(
        default=None,
        description="The Anatel rating of the content.",
        alias="anatelRating",
    )
    bbfc_rating: Optional[StrictStr] = Field(
        default=None, description="The BBFC rating of the content.", alias="bbfcRating"
    )
    bfvc_rating: Optional[StrictStr] = Field(
        default=None, description="The BFVC rating of the content.", alias="bfvcRating"
    )
    bmukk_rating: Optional[StrictStr] = Field(
        default=None,
        description="The BMUKK rating of the content.",
        alias="bmukkRating",
    )
    catv_rating: Optional[StrictStr] = Field(
        default=None, description="The CATV rating of the content.", alias="catvRating"
    )
    catvfr_rating: Optional[StrictStr] = Field(
        default=None,
        description="The CATVFR rating of the content.",
        alias="catvfrRating",
    )
    cbfc_rating: Optional[StrictStr] = Field(
        default=None, description="The CBFC rating of the content.", alias="cbfcRating"
    )
    ccc_rating: Optional[StrictStr] = Field(
        default=None, description="The CCC rating of the content.", alias="cccRating"
    )
    cce_rating: Optional[StrictStr] = Field(
        default=None, description="The CCE rating of the content.", alias="cceRating"
    )
    chfilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The CHFilm rating of the content.",
        alias="chfilmRating",
    )
    chvrs_rating: Optional[StrictStr] = Field(
        default=None,
        description="The CHVRS rating of the content.",
        alias="chvrsRating",
    )
    cicf_rating: Optional[StrictStr] = Field(
        default=None, description="The CICF rating of the content.", alias="cicfRating"
    )
    cna_rating: Optional[StrictStr] = Field(
        default=None, description="The CNA rating of the content.", alias="cnaRating"
    )
    cnc_rating: Optional[StrictStr] = Field(
        default=None, description="The CNC rating of the content.", alias="cncRating"
    )
    csa_rating: Optional[StrictStr] = Field(
        default=None, description="The CSA rating of the content.", alias="csaRating"
    )
    cscf_rating: Optional[StrictStr] = Field(
        default=None, description="The CSCF rating of the content.", alias="cscfRating"
    )
    czfilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The CZFilm rating of the content.",
        alias="czfilmRating",
    )
    djctq_rating: Optional[StrictStr] = Field(
        default=None,
        description="The DJCTQ rating of the content.",
        alias="djctqRating",
    )
    djctq_rating_reasons: Optional[List[StrictStr]] = Field(
        default=None, alias="djctqRatingReasons"
    )
    ecbmct_rating: Optional[StrictStr] = Field(
        default=None,
        description="The ECBMCT rating of the content.",
        alias="ecbmctRating",
    )
    eefilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The EEFilm rating of the content.",
        alias="eefilmRating",
    )
    egfilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The EGFilm rating of the content.",
        alias="egfilmRating",
    )
    eirin_rating: Optional[StrictStr] = Field(
        default=None,
        description="The EIRIN rating of the content.",
        alias="eirinRating",
    )
    fcbm_rating: Optional[StrictStr] = Field(
        default=None, description="The FCBM rating of the content.", alias="fcbmRating"
    )
    fco_rating: Optional[StrictStr] = Field(
        default=None, description="The FCO rating of the content.", alias="fcoRating"
    )
    fmoc_rating: Optional[StrictStr] = Field(
        default=None,
        description="The FMOC rating of the content. This property has been deprecated as of November 2, 2015. Use the `contentDetails.contentRating.cncRating` property instead.",
        alias="fmocRating",
    )
    fpb_rating: Optional[StrictStr] = Field(
        default=None, description="The FPB rating of the content.", alias="fpbRating"
    )
    fpb_rating_reasons: Optional[List[StrictStr]] = Field(
        default=None, alias="fpbRatingReasons"
    )
    fsk_rating: Optional[StrictStr] = Field(
        default=None, description="The FSK rating of the content.", alias="fskRating"
    )
    grfilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The GRFilm rating of the content.",
        alias="grfilmRating",
    )
    icaa_rating: Optional[StrictStr] = Field(
        default=None, description="The ICAA rating of the content.", alias="icaaRating"
    )
    ifco_rating: Optional[StrictStr] = Field(
        default=None, description="The IFCo rating of the content.", alias="ifcoRating"
    )
    ilfilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The ILFilm rating of the content.",
        alias="ilfilmRating",
    )
    incaa_rating: Optional[StrictStr] = Field(
        default=None,
        description="The INCAA rating of the content.",
        alias="incaaRating",
    )
    kfcb_rating: Optional[StrictStr] = Field(
        default=None, description="The KFCB rating of the content.", alias="kfcbRating"
    )
    kijkwijzer_rating: Optional[StrictStr] = Field(
        default=None,
        description="The Kijkwijzer rating of the content.",
        alias="kijkwijzerRating",
    )
    kmrb_rating: Optional[StrictStr] = Field(
        default=None, description="The KMRB rating of the content.", alias="kmrbRating"
    )
    lsf_rating: Optional[StrictStr] = Field(
        default=None, description="The LSF rating of the content.", alias="lsfRating"
    )
    mccaa_rating: Optional[StrictStr] = Field(
        default=None,
        description="The MCCAA rating of the content.",
        alias="mccaaRating",
    )
    mccyp_rating: Optional[StrictStr] = Field(
        default=None,
        description="The MCCYP rating of the content.",
        alias="mccypRating",
    )
    mcst_rating: Optional[StrictStr] = Field(
        default=None, description="The MCST rating of the content.", alias="mcstRating"
    )
    mda_rating: Optional[StrictStr] = Field(
        default=None, description="The MDA rating of the content.", alias="mdaRating"
    )
    medietilsynet_rating: Optional[StrictStr] = Field(
        default=None,
        description="The Medietilsynet rating of the content.",
        alias="medietilsynetRating",
    )
    meku_rating: Optional[StrictStr] = Field(
        default=None, description="The MEKU rating of the content.", alias="mekuRating"
    )
    mibac_rating: Optional[StrictStr] = Field(
        default=None,
        description="The MIBAC rating of the content.",
        alias="mibacRating",
    )
    moc_rating: Optional[StrictStr] = Field(
        default=None, description="The MOC rating of the content.", alias="mocRating"
    )
    moctw_rating: Optional[StrictStr] = Field(
        default=None,
        description="The MOCTW rating of the content.",
        alias="moctwRating",
    )
    mpaa_rating: Optional[StrictStr] = Field(
        default=None, description="The MPAA rating of the content.", alias="mpaaRating"
    )
    mpaat_rating: Optional[StrictStr] = Field(
        default=None,
        description="The MPAAT rating of the content.",
        alias="mpaatRating",
    )
    mtrcb_rating: Optional[StrictStr] = Field(
        default=None,
        description="The MTRCB rating of the content.",
        alias="mtrcbRating",
    )
    nbc_rating: Optional[StrictStr] = Field(
        default=None, description="The NBC rating of the content.", alias="nbcRating"
    )
    nbcpl_rating: Optional[StrictStr] = Field(
        default=None,
        description="The NBCPL rating of the content.",
        alias="nbcplRating",
    )
    nfrc_rating: Optional[StrictStr] = Field(
        default=None, description="The NFRC rating of the content.", alias="nfrcRating"
    )
    nfvcb_rating: Optional[StrictStr] = Field(
        default=None,
        description="The NFVCB rating of the content.",
        alias="nfvcbRating",
    )
    nkclv_rating: Optional[StrictStr] = Field(
        default=None,
        description="The NKCLV rating of the content.",
        alias="nkclvRating",
    )
    oflc_rating: Optional[StrictStr] = Field(
        default=None, description="The OFLC rating of the content.", alias="oflcRating"
    )
    pefilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The PEFilm rating of the content.",
        alias="pefilmRating",
    )
    rcnof_rating: Optional[StrictStr] = Field(
        default=None,
        description="The RCNOF rating of the content.",
        alias="rcnofRating",
    )
    resorteviolencia_rating: Optional[StrictStr] = Field(
        default=None,
        description="The RESORTEVIOLÊNCIA rating of the content.",
        alias="resorteviolenciaRating",
    )
    rtc_rating: Optional[StrictStr] = Field(
        default=None, description="The RTC rating of the content.", alias="rtcRating"
    )
    rte_rating: Optional[StrictStr] = Field(
        default=None, description="The RTE rating of the content.", alias="rteRating"
    )
    russia_rating: Optional[StrictStr] = Field(
        default=None,
        description="The Russia rating of the content.",
        alias="russiaRating",
    )
    skfilm_rating: Optional[StrictStr] = Field(
        default=None,
        description="The SKFilm rating of the content.",
        alias="skfilmRating",
    )
    smais_rating: Optional[StrictStr] = Field(
        default=None,
        description="The SMAIS rating of the content.",
        alias="smaisRating",
    )
    smsa_rating: Optional[StrictStr] = Field(
        default=None, description="The SMSA rating of the content.", alias="smsaRating"
    )
    tvpg_rating: Optional[StrictStr] = Field(
        default=None, description="The TVPG rating of the content.", alias="tvpgRating"
    )
    yt_rating: Optional[StrictStr] = Field(
        default=None, description="The YT rating of the content.", alias="ytRating"
    )
    __properties: ClassVar[List[str]] = [
        "acbRating",
        "agcomRating",
        "anatelRating",
        "bbfcRating",
        "bfvcRating",
        "bmukkRating",
        "catvRating",
        "catvfrRating",
        "cbfcRating",
        "cccRating",
        "cceRating",
        "chfilmRating",
        "chvrsRating",
        "cicfRating",
        "cnaRating",
        "cncRating",
        "csaRating",
        "cscfRating",
        "czfilmRating",
        "djctqRating",
        "djctqRatingReasons",
        "ecbmctRating",
        "eefilmRating",
        "egfilmRating",
        "eirinRating",
        "fcbmRating",
        "fcoRating",
        "fmocRating",
        "fpbRating",
        "fpbRatingReasons",
        "fskRating",
        "grfilmRating",
        "icaaRating",
        "ifcoRating",
        "ilfilmRating",
        "incaaRating",
        "kfcbRating",
        "kijkwijzerRating",
        "kmrbRating",
        "lsfRating",
        "mccaaRating",
        "mccypRating",
        "mcstRating",
        "mdaRating",
        "medietilsynetRating",
        "mekuRating",
        "mibacRating",
        "mocRating",
        "moctwRating",
        "mpaaRating",
        "mpaatRating",
        "mtrcbRating",
        "nbcRating",
        "nbcplRating",
        "nfrcRating",
        "nfvcbRating",
        "nkclvRating",
        "oflcRating",
        "pefilmRating",
        "rcnofRating",
        "resorteviolenciaRating",
        "rtcRating",
        "rteRating",
        "russiaRating",
        "skfilmRating",
        "smaisRating",
        "smsaRating",
        "tvpgRating",
        "ytRating",
    ]

    model_config = {"populate_by_name": True, "validate_assignment": True}

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContentRating from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ContentRating from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "acbRating": obj.get("acbRating"),
                "agcomRating": obj.get("agcomRating"),
                "anatelRating": obj.get("anatelRating"),
                "bbfcRating": obj.get("bbfcRating"),
                "bfvcRating": obj.get("bfvcRating"),
                "bmukkRating": obj.get("bmukkRating"),
                "catvRating": obj.get("catvRating"),
                "catvfrRating": obj.get("catvfrRating"),
                "cbfcRating": obj.get("cbfcRating"),
                "cccRating": obj.get("cccRating"),
                "cceRating": obj.get("cceRating"),
                "chfilmRating": obj.get("chfilmRating"),
                "chvrsRating": obj.get("chvrsRating"),
                "cicfRating": obj.get("cicfRating"),
                "cnaRating": obj.get("cnaRating"),
                "cncRating": obj.get("cncRating"),
                "csaRating": obj.get("csaRating"),
                "cscfRating": obj.get("cscfRating"),
                "czfilmRating": obj.get("czfilmRating"),
                "djctqRating": obj.get("djctqRating"),
                "djctqRatingReasons": obj.get("djctqRatingReasons"),
                "ecbmctRating": obj.get("ecbmctRating"),
                "eefilmRating": obj.get("eefilmRating"),
                "egfilmRating": obj.get("egfilmRating"),
                "eirinRating": obj.get("eirinRating"),
                "fcbmRating": obj.get("fcbmRating"),
                "fcoRating": obj.get("fcoRating"),
                "fmocRating": obj.get("fmocRating"),
                "fpbRating": obj.get("fpbRating"),
                "fpbRatingReasons": obj.get("fpbRatingReasons"),
                "fskRating": obj.get("fskRating"),
                "grfilmRating": obj.get("grfilmRating"),
                "icaaRating": obj.get("icaaRating"),
                "ifcoRating": obj.get("ifcoRating"),
                "ilfilmRating": obj.get("ilfilmRating"),
                "incaaRating": obj.get("incaaRating"),
                "kfcbRating": obj.get("kfcbRating"),
                "kijkwijzerRating": obj.get("kijkwijzerRating"),
                "kmrbRating": obj.get("kmrbRating"),
                "lsfRating": obj.get("lsfRating"),
                "mccaaRating": obj.get("mccaaRating"),
                "mccypRating": obj.get("mccypRating"),
                "mcstRating": obj.get("mcstRating"),
                "mdaRating": obj.get("mdaRating"),
                "medietilsynetRating": obj.get("medietilsynetRating"),
                "mekuRating": obj.get("mekuRating"),
                "mibacRating": obj.get("mibacRating"),
                "mocRating": obj.get("mocRating"),
                "moctwRating": obj.get("moctwRating"),
                "mpaaRating": obj.get("mpaaRating"),
                "mpaatRating": obj.get("mpaatRating"),
                "mtrcbRating": obj.get("mtrcbRating"),
                "nbcRating": obj.get("nbcRating"),
                "nbcplRating": obj.get("nbcplRating"),
                "nfrcRating": obj.get("nfrcRating"),
                "nfvcbRating": obj.get("nfvcbRating"),
                "nkclvRating": obj.get("nkclvRating"),
                "oflcRating": obj.get("oflcRating"),
                "pefilmRating": obj.get("pefilmRating"),
                "rcnofRating": obj.get("rcnofRating"),
                "resorteviolenciaRating": obj.get("resorteviolenciaRating"),
                "rtcRating": obj.get("rtcRating"),
                "rteRating": obj.get("rteRating"),
                "russiaRating": obj.get("russiaRating"),
                "skfilmRating": obj.get("skfilmRating"),
                "smaisRating": obj.get("smaisRating"),
                "smsaRating": obj.get("smsaRating"),
                "tvpgRating": obj.get("tvpgRating"),
                "ytRating": obj.get("ytRating"),
            }
        )
        return _obj
