# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from openapi_client.models.thumbnail import Thumbnail


class TestThumbnail(unittest.TestCase):
    """Thumbnail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Thumbnail:
        """Test Thumbnail
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Thumbnail`
        """
        model = Thumbnail()
        if include_optional:
            return Thumbnail(
                url = '',
                width = 56,
                height = 56
            )
        else:
            return Thumbnail(
        )
        """

    def testThumbnail(self):
        """Test Thumbnail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
