# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import unittest

from openapi_client.api.captions_api import CaptionsApi


class TestCaptionsApi(unittest.TestCase):
    """CaptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaptionsApi()

    def tearDown(self) -> None:
        pass

    def test_captions_download(self) -> None:
        """Test case for captions_download

        Downloads a caption track.
        """
        pass

    def test_captions_list(self) -> None:
        """Test case for captions_list

        Returns a list of caption tracks associated with a given video.
        """
        pass


if __name__ == "__main__":
    unittest.main()
