# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from openapi_client.models.caption_list import CaptionList


class TestCaptionList(unittest.TestCase):
    """CaptionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaptionList:
        """Test CaptionList
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CaptionList`
        """
        model = CaptionList()
        if include_optional:
            return CaptionList(
                kind = '',
                etag = '',
                items = [
                    openapi_client.models.caption.Caption(
                        kind = '',
                        etag = '',
                        id = '',
                        snippet = openapi_client.models.caption_snippet.Caption_snippet(
                            video_id = '',
                            last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                            track_kind = 'standard',
                            language = '',
                            name = '',
                            audio_track_type = 'unknown',
                            is_cc = True,
                            is_large = True,
                            is_easy_reader = True,
                            is_draft = True,
                            is_auto_synced = True,
                            status = 'failed',
                            failure_reason = 'processingFailed', ), )
                    ]
            )
        else:
            return CaptionList(
        )
        """

    def testCaptionList(self):
        """Test CaptionList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
