# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from openapi_client.models.file_details_audio_streams_inner import (
    FileDetailsAudioStreamsInner,
)


class TestFileDetailsAudioStreamsInner(unittest.TestCase):
    """FileDetailsAudioStreamsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileDetailsAudioStreamsInner:
        """Test FileDetailsAudioStreamsInner
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FileDetailsAudioStreamsInner`
        """
        model = FileDetailsAudioStreamsInner()
        if include_optional:
            return FileDetailsAudioStreamsInner(
                channel_count = 56,
                codec = '',
                bitrate_bps = 56,
                vendor = ''
            )
        else:
            return FileDetailsAudioStreamsInner(
        )
        """

    def testFileDetailsAudioStreamsInner(self):
        """Test FileDetailsAudioStreamsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
