# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from openapi_client.models.video_category_list import VideoCategoryList


class TestVideoCategoryList(unittest.TestCase):
    """VideoCategoryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoCategoryList:
        """Test VideoCategoryList
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `VideoCategoryList`
        """
        model = VideoCategoryList()
        if include_optional:
            return VideoCategoryList(
                kind = '',
                etag = '',
                next_page_token = '',
                prev_page_token = '',
                page_info = openapi_client.models.page_info.PageInfo(
                    total_results = 56,
                    results_per_page = 56, ),
                items = [
                    openapi_client.models.video_category.VideoCategory(
                        kind = '',
                        etag = '',
                        id = '',
                        snippet = openapi_client.models.video_category_snippet.VideoCategorySnippet(
                            channel_id = '',
                            title = '',
                            assignable = True, ), )
                    ]
            )
        else:
            return VideoCategoryList(
        )
        """

    def testVideoCategoryList(self):
        """Test VideoCategoryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
