# coding: utf-8
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
import datetime
import unittest

from openapi_client.models.content_rating import ContentRating


class TestContentRating(unittest.TestCase):
    """ContentRating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentRating:
        """Test ContentRating
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ContentRating`
        """
        model = ContentRating()
        if include_optional:
            return ContentRating(
                acb_rating = '',
                agcom_rating = '',
                anatel_rating = '',
                bbfc_rating = '',
                bfvc_rating = '',
                bmukk_rating = '',
                catv_rating = '',
                catvfr_rating = '',
                cbfc_rating = '',
                ccc_rating = '',
                cce_rating = '',
                chfilm_rating = '',
                chvrs_rating = '',
                cicf_rating = '',
                cna_rating = '',
                cnc_rating = '',
                csa_rating = '',
                cscf_rating = '',
                czfilm_rating = '',
                djctq_rating = '',
                djctq_rating_reasons = [
                    ''
                    ],
                ecbmct_rating = '',
                eefilm_rating = '',
                egfilm_rating = '',
                eirin_rating = '',
                fcbm_rating = '',
                fco_rating = '',
                fmoc_rating = '',
                fpb_rating = '',
                fpb_rating_reasons = [
                    ''
                    ],
                fsk_rating = '',
                grfilm_rating = '',
                icaa_rating = '',
                ifco_rating = '',
                ilfilm_rating = '',
                incaa_rating = '',
                kfcb_rating = '',
                kijkwijzer_rating = '',
                kmrb_rating = '',
                lsf_rating = '',
                mccaa_rating = '',
                mccyp_rating = '',
                mcst_rating = '',
                mda_rating = '',
                medietilsynet_rating = '',
                meku_rating = '',
                mibac_rating = '',
                moc_rating = '',
                moctw_rating = '',
                mpaa_rating = '',
                mpaat_rating = '',
                mtrcb_rating = '',
                nbc_rating = '',
                nbcpl_rating = '',
                nfrc_rating = '',
                nfvcb_rating = '',
                nkclv_rating = '',
                oflc_rating = '',
                pefilm_rating = '',
                rcnof_rating = '',
                resorteviolencia_rating = '',
                rtc_rating = '',
                rte_rating = '',
                russia_rating = '',
                skfilm_rating = '',
                smais_rating = '',
                smsa_rating = '',
                tvpg_rating = '',
                yt_rating = ''
            )
        else:
            return ContentRating(
        )
        """

    def testContentRating(self):
        """Test ContentRating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
