# coding: utf-8
# flake8: noqa
"""
    YouTube Data API v3

    See. [YouTube Data API v3](https://developers.google.com/youtube/v3)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
# import models into model package
from youtube_data_v3.models.caption import Caption
from youtube_data_v3.models.caption_list import CaptionList
from youtube_data_v3.models.caption_snippet import CaptionSnippet
from youtube_data_v3.models.content_details import ContentDetails
from youtube_data_v3.models.content_details_region_restriction import (
    ContentDetailsRegionRestriction,
)
from youtube_data_v3.models.content_rating import ContentRating
from youtube_data_v3.models.file_details import FileDetails
from youtube_data_v3.models.file_details_audio_streams_inner import (
    FileDetailsAudioStreamsInner,
)
from youtube_data_v3.models.file_details_video_streams_inner import (
    FileDetailsVideoStreamsInner,
)
from youtube_data_v3.models.live_streaming_details import LiveStreamingDetails
from youtube_data_v3.models.localization_value import LocalizationValue
from youtube_data_v3.models.localized import Localized
from youtube_data_v3.models.page_info import PageInfo
from youtube_data_v3.models.player import Player
from youtube_data_v3.models.processing_details import ProcessingDetails
from youtube_data_v3.models.processing_details_processing_progress import (
    ProcessingDetailsProcessingProgress,
)
from youtube_data_v3.models.recording_details import RecordingDetails
from youtube_data_v3.models.snippet import Snippet
from youtube_data_v3.models.statistics import Statistics
from youtube_data_v3.models.status import Status
from youtube_data_v3.models.suggestions import Suggestions
from youtube_data_v3.models.suggestions_tag_suggestions_inner import (
    SuggestionsTagSuggestionsInner,
)
from youtube_data_v3.models.thumbnail import Thumbnail
from youtube_data_v3.models.topic_details import TopicDetails
from youtube_data_v3.models.video import Video
from youtube_data_v3.models.video_category import VideoCategory
from youtube_data_v3.models.video_category_list import VideoCategoryList
from youtube_data_v3.models.video_category_snippet import VideoCategorySnippet
from youtube_data_v3.models.video_list import VideoList
