name: CI for Back-End

on:
  workflow_dispatch:
  push:
    paths:
      - "pulumi/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v3
      - name: Git Secret Reveal
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-private-key-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - name: Read env file and set variables
        uses: cosq-network/dotenv-loader@v1.0.2
        with:
          env-file: pulumi/.env
