name: CI for Back-End

on:
  workflow_dispatch:
  push:
    paths:
      - "pulumi/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Git Secret Reveal
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-private-key-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - name: Load pulumi/.env
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: pulumi/.env
          mask-variables: true
      - run: pip install -r requirements.txt
        working-directory: pulumi
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ steps.dotenv.outputs.GOOGLE_CREDENTIALS }}
