name: CI for Front-End

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v3
      - name: Install git-secret
        run: |
          sudo sh -c "echo 'deb https://gitsecret.jfrog.io/artifactory/git-secret-deb git-secret main' >> /etc/apt/sources.list"
          wget -qO - https://gitsecret.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y git-secret && git-secret --version
