name: CI for Front-End

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "pulumi/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Git Secret Reveal
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-private-key-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
