name: CI for Front-End

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "**.toml"
      - "**.yml"
      - "**.yaml"
      - "pulumi/**"
      - "functions/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Git Secret Reveal
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-private-key-passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: make build
      - name: Deploy to Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref != 'refs/heads/main'
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOMUTUBE_F5B5D }}"
          projectId: yomutube-f5b5d
          channelId: preview
          expires: 7d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: Deploy to Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'refs/heads/main'
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOMUTUBE_F5B5D }}"
          projectId: yomutube-f5b5d
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
